### ISSUE TITLE
Q: read the last FENCE token without incrementing?

### ISSUE THREAD

**Issue by glycerine** [tidwall/summitdb#10]
To check if I have won an election, I'd like to read the value of the FENCE counter -- without adding to the fence token. Is this possible?

2nd question: is it possible to listen on a FENCE for changes, or does one need to poll?

**Comment by tidwall** [comment]
> To check if I have won an election, I'd like to read the value of the FENCE counter -- without adding to the fence token. Is this possible?

No. Right now it's only possible to increment the token and get the new value back.

I would be trivial to add this feature, perhaps:

```
FENCE token PEEK
```

could return the current token value.

> 2nd question: is it possible to listen on a FENCE for changes, or does one need to poll?

At this time there's no way to listen for changes.
