### ISSUE TITLE
compare with Aerospike?

### ISSUE THREAD

**Issue by fengyuncrawl** [tidwall/summitdb#2]

**Comment by tidwall** [comment]
I'm sorry but I'm not familiar with Aerospike.

**Comment by fengyuncrawl** [comment]
supporting SSD plan for the future ?

**Comment by tidwall** [comment]
Are you asking if SummitDB will support using SSD (instead of memory) for data storage?

If so, I have been exploring using BoltDB as an optional backend. There an open question regarding this [here](https://github.com/tidwall/summitdb/issues/1).

Though at this time it's not a priority.

**Comment by fengyuncrawl** [comment]
yes
