### ISSUE TITLE
support for list data structure

### ISSUE THREAD

**Issue by komuW** [tidwall/summitdb#22]
Hi,
I would like to create a message broker/queue on top of summitDB. 
I can see that everything in summitDB is essentially a string, I wanted to know if you have plans of adding other structures like lists. 
This would make it easier to create a queue via `RPUSH` and `LPOP`  or `rpoplpush`[1] .

Alternatively, if you have no plans of adding lists. Do you have ideas how I would emulate a queue using strings? 😩 
I was thinking;
1. create a queue as a string
`./redis-cli -p 7481 SET mykeyQueue "foo bar baz"`

2. get item from queue
`./redis-cli -p 7481 GET mykeyQueue`

3. perfom RPUSH in golang
```go
myStr := "foo bar  baz"
myList := strings.Fields(myStr)
myList := append(myList, "newValue") // this is equivalent to RPUSH
// convert back to string
myStr := strings.Join(myList, " ")
```
4. set it back into the queue
`./redis-cli -p 7481 SET mykeyQueue "foo bar baz newValue"`

... performing LPOP will be kind of the opposite of the above.      

thoughts??
Or should I use the builtin json[2] support to create my queue instead.  

1. https://redis.io/commands/rpoplpush#pattern-reliable-queue
2. https://github.com/tidwall/summitdb#json-documents

**Comment by komuW** [comment]
cc @tidwall

**Comment by tidwall** [comment]
Unfortunately I don't have any plans for adding list commands at this time. 

One idea is to use the json commands inside a script.

For example and RPUSH could be:

```
> script load "sdb.call('set', KEYS[0], '[]', 'nx');sdb.call('jset', KEYS[0], '-1', ARGV[0]);return parseInt(sdb.call('jget', KEYS[0], '#'));"
"95e4005b8d5dff3778154ae39dd819a21c363d13"
```

Then you can use the script like:

```
> evalsha 95e4005b8d5dff3778154ae39dd819a21c363d13 1 mylist item1
1
> evalsha 95e4005b8d5dff3778154ae39dd819a21c363d13 1 mylist item2
2
> evalsha 95e4005b8d5dff3778154ae39dd819a21c363d13 1 mylist item3
3
> evalsha 95e4005b8d5dff3778154ae39dd819a21c363d13 1 mylist item4
4
```
For LPOP:

```
> script load "var res = sdb.call('jget', KEYS[0], '0');sdb.call('jdel', KEYS[0], '0');return res;"
"e3f15d9503ca033132d0e83b35ec3afcf28ef922"
```

```
> evalsha e3f15d9503ca033132d0e83b35ec3afcf28ef922 1 mylist
"item1"
> evalsha e3f15d9503ca033132d0e83b35ec3afcf28ef922 1 mylist
"item2"
> evalsha e3f15d9503ca033132d0e83b35ec3afcf28ef922 1 mylist
"item3"
> evalsha e3f15d9503ca033132d0e83b35ec3afcf28ef922 1 mylist
"item4"
> evalsha e3f15d9503ca033132d0e83b35ec3afcf28ef922 1 mylist
(nil)
```

The underlying data is just a json array. So you can get the entire list with a GET:

```
> evalsha 95e4005b8d5dff3778154ae39dd819a21c363d13 1 mylist item1
1
> evalsha 95e4005b8d5dff3778154ae39dd819a21c363d13 1 mylist item2
2
> GET mylist
"[\"item1\",\"item2\"]"
```

**Comment by komuW** [comment]
thanks
