### ISSUE TITLE
Will you support authentication and TLS?

### ISSUE THREAD

**Issue by didip** [tidwall/summitdb#26]
Hi, first of all, thank you for creating this DB. It's the perfect use case for us.

However, I don't see TLS certs and authentication options on `summitdb-server`. It looks like `redcon` already supports TLS, so maybe it's just a simple upgrade?

That said, I don't see `summitdb` supporting `AUTH` command yet. It would be super cool if you are willing to consider adding this option. It's difficult for me to sell it without authentication feature.

**Comment by tidwall** [comment]
Sorry, but I'm not going to add TLS directly to SummitDB. I recommend checking out stunnel, which gives tunnels TLS over TCP.

I may consider AUTH in the future.

Thanks for your suggestions.
