### ISSUE TITLE
FYI: works fine on AArch64...

### ISSUE THREAD

**Issue by rhenwood-arm** [tidwall/summitdb#29]
Hi @tidwall ,

I've been looking at SummitDB and found it ran just fine on AArch64. This eventuality is not normally something I consider comment-worthy. However, in this case an initial run didn't look great so I opened an issue asking if this project was maintained. Given that this project is maintained, and it runs fine on AArch64, I thought it only polite to document it here and conclude this episode. :)

**Comment by tidwall** [comment]
That's great to hear! And thanks for following up.
