### ISSUE TITLE
Is it neccessary to open buntdb in file mode?

### ISSUE THREAD

**Issue by joe-zxh** [tidwall/summitdb#32]
Hi, Tidwall! This is an excellent project, but something confuses me.

In machine.go("line 134, db, err := buntdb.Open(file)"), the buntdb is opening in file mode rather than the pure memory mode.

It seems that the only usage of the buntdb database file is to generate the Raft snapshot. (Am I correct? Maybe I have missed something)

However, the Raft snapshot may generate from the Raft peer's log(/data/raft.db) together with its last snapshot files.

It seems redundant to log the command twice in both the raft's log and the buntdb. It may influence the performance of summitdb.

Thank you, and I look forward to hearing from you.

**Comment by tidwall** [comment]
The Raft log does not contain every command for all time.  The log needs to be occasionally compacted. When this happens the local database is must be snapshotted. That snapshot is backed by a real database, which in this case is buntdb.

**Comment by joe-zxh** [comment]
I know when the log need to be truncated, the Raft peer will do the snapshot. But I think the current log and the last snapshot could provide enough information for the next snapshot.

Though the current log may be truncated before and do not have the complete log entries, yet the commands in the last snapshot should contain the missing log entries. Then the next Raft snapshot may generate from the Raft peer's log together with its last snapshot files.

Thank you, and I look forward to hearing from you.

**Comment by joe-zxh** [comment]
Will SummitDB truncate the Raft log automatically?(or do the snapshot automatically)

The log mode in SummitDB for Raft is FastLog, which may have problem when the Raft peer run out of memory.
